import urllib.request
import json

def generate_custom_blocks(extracted_data):
    """Generates PoE filter syntax blocks from extracted PoB data."""
    blocks = []
    blocks.append("# ==========================================================================")
    blocks.append("# CUSTOM BUILD OVERRIDES (Generated by PoE Loot Filter Creator)")
    blocks.append("# ==========================================================================")
    blocks.append("")
    
    bases = extracted_data.get('bases', set())
    if bases:
        blocks.append("Show # Highlighting Build-Specific Bases")
        blocks.append(f"    BaseType {' '.join(['\"' + b + '\"' for b in sorted(bases)])}")
        blocks.append("    Rarity <= Rare")
        blocks.append("    SetBorderColor 0 255 0 255") # Green border
        blocks.append("    SetFontSize 40")
        blocks.append("    MinimapIcon 1 Green Star")
        blocks.append("    PlayAlertSound 2 300")
        blocks.append("")
        
    socket_groups = extracted_data.get('socket_groups', set())
    if socket_groups:
        for sg in sorted(socket_groups):
            if len(sg) >= 4: # Only highlight 4+ links
                blocks.append(f"Show # Highlighting Socket Group: {sg}")
                blocks.append(f"    SocketGroup {sg}")
                blocks.append(f"    LinkedSockets >= {len(sg)}")
                blocks.append("    SetBorderColor 0 255 255 255") # Cyan border
                blocks.append("    MinimapIcon 2 Cyan Diamond")
                blocks.append("")
            
    blocks.append("# ==========================================================================")
    blocks.append("# END OF CUSTOM BUILD OVERRIDES")
    blocks.append("# ==========================================================================")
    blocks.append("")
    return "\n".join(blocks)

def fetch_neversink_latest():
    """Fetches the latest 1_Regular.filter release from NeverSink's GitHub."""
    url = "https://api.github.com/repos/NeverSinkDev/NeverSink-Filter/releases/latest"
    req = urllib.request.Request(url, headers={'User-Agent': 'poe-loot-filter-creator'})
    try:
        with urllib.request.urlopen(req) as response:
            data = json.loads(response.read().decode())
            
            download_url = None
            for asset in data.get('assets', []):
                if asset['name'] == '1_Regular.filter':
                    download_url = asset['browser_download_url']
                    break
            
            if download_url:
                req2 = urllib.request.Request(download_url, headers={'User-Agent': 'poe-loot-filter-creator'})
                with urllib.request.urlopen(req2) as resp2:
                    # Return the raw filter text
                    return resp2.read().decode('utf-8')
    except Exception as e:
        print(f"Error fetching NeverSink filter: {e}")
        return "# Error fetching base filter. Please append custom rules manually."

def assemble_filter(extracted_data, base_filter_text=None):
    """Combines custom blocks with the base filter."""
    custom_rules = generate_custom_blocks(extracted_data)
    if base_filter_text is None:
        base_filter_text = fetch_neversink_latest()
        
    return custom_rules + "\n" + base_filter_text
