import urllib.request
import json

def generate_custom_blocks(extracted_data):
    """Generates PoE filter syntax blocks from extracted PoB data."""
    blocks = []
    blocks.append("# ==========================================================================")
    blocks.append("# CUSTOM BUILD OVERRIDES (Generated by PoE Loot Filter Creator)")
    blocks.append("# ==========================================================================")
    blocks.append("")
    
    bases = extracted_data.get('bases', set())
    if bases:
        blocks.append("Show # Highlighting Build-Specific Bases")
        blocks.append(f"    BaseType {' '.join(['\"' + b + '\"' for b in sorted(bases)])}")
        blocks.append("    Rarity <= Rare")
        blocks.append("    SetBorderColor 0 255 0 255") # Green border
        blocks.append("    SetFontSize 40")
        blocks.append("    MinimapIcon 1 Green Star")
        blocks.append("    PlayAlertSound 2 300")
        blocks.append("")
        
    socket_groups = extracted_data.get('socket_groups', set())
    if socket_groups:
        for sg in sorted(socket_groups):
            if len(sg) >= 4: # Only highlight 4+ links
                blocks.append(f"Show # Highlighting Socket Group: {sg}")
                blocks.append(f"    SocketGroup {sg}")
                blocks.append(f"    LinkedSockets >= {len(sg)}")
                blocks.append("    SetBorderColor 0 255 255 255") # Cyan border
                blocks.append("    MinimapIcon 2 Cyan Diamond")
                blocks.append("")
            
    blocks.append("# ==========================================================================")
    blocks.append("# END OF CUSTOM BUILD OVERRIDES")
    blocks.append("# ==========================================================================")
    blocks.append("")
    return "\n".join(blocks)

def fetch_neversink_latest():
    """Fetches the latest source from NeverSink's GitHub and extracts 1_Regular.filter."""
    # Since recent releases don't have built assets, we fetch the source zipball
    # and find the 1_Regular.filter within it.
    tag_url = "https://api.github.com/repos/NeverSinkDev/NeverSink-Filter/releases/latest"
    
    import ssl
    import zipfile
    import io
    
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    req = urllib.request.Request(tag_url, headers={'User-Agent': 'poe-loot-filter-creator'})
    try:
        with urllib.request.urlopen(req, context=ctx) as response:
            data = json.loads(response.read().decode())
            zip_url = data.get('zipball_url')
            
            if zip_url:
                req2 = urllib.request.Request(zip_url, headers={'User-Agent': 'poe-loot-filter-creator'})
                with urllib.request.urlopen(req2, context=ctx) as resp2:
                    zip_data = resp2.read()
                    with zipfile.ZipFile(io.BytesIO(zip_data)) as z:
                        # Find the 1_Regular.filter file inside the zip
                        # GitHub zipballs have a top-level folder like NeverSink-Filter-tagname/
                        for file_path in z.namelist():
                            if file_path.endswith('1_Regular.filter'):
                                with z.open(file_path) as f:
                                    return f.read().decode('utf-8')
    except Exception as e:
        import traceback
        print(f"DEBUG: NeverSink Fetch Exception: {e}")
        print(traceback.format_exc())
        raise e
    
    return None

def assemble_filter(extracted_data, base_filter_text=None):
    """Combines custom blocks with the base filter."""
    custom_rules = generate_custom_blocks(extracted_data)
    if base_filter_text is None:
        base_filter_text = fetch_neversink_latest()
        
    return custom_rules + "\n" + base_filter_text
