import urllib.request
import json

def generate_custom_blocks(extracted_data):
    """Generates PoE filter syntax blocks from extracted PoB data."""
    blocks = []
    blocks.append("# ==========================================================================")
    blocks.append("# CUSTOM BUILD OVERRIDES (Generated by PoE Loot Filter Creator)")
    blocks.append("# ==========================================================================")
    blocks.append("")
    
    bases = extracted_data.get('bases', set())
    if bases:
        blocks.append("Show # Highlighting Build-Specific Bases")
        blocks.append(f"    BaseType {' '.join(['\"' + b + '\"' for b in sorted(bases)])}")
        blocks.append("    Rarity <= Rare")
        blocks.append("    SetBorderColor 0 255 0 255") # Green border
        blocks.append("    SetFontSize 40")
        blocks.append("    MinimapIcon 1 Green Star")
        blocks.append("    PlayAlertSound 2 300")
        blocks.append("")
        
    socket_groups = extracted_data.get('socket_groups', set())
    if socket_groups:
        for sg in sorted(socket_groups):
            if len(sg) >= 4: # Only highlight 4+ links
                blocks.append(f"Show # Highlighting Socket Group: {sg}")
                blocks.append(f"    SocketGroup {sg}")
                blocks.append(f"    LinkedSockets >= {len(sg)}")
                blocks.append("    SetBorderColor 0 255 255 255") # Cyan border
                blocks.append("    MinimapIcon 2 Cyan Diamond")
                blocks.append("")
            
    blocks.append("# ==========================================================================")
    blocks.append("# END OF CUSTOM BUILD OVERRIDES")
    blocks.append("# ==========================================================================")
    blocks.append("")
    return "\n".join(blocks)

import os
import time

def fetch_neversink_latest():
    """Fetches the latest source from NeverSink's GitHub and extracts 1-REGULAR.filter."""
    tag_url = "https://api.github.com/repos/NeverSinkDev/NeverSink-Filter/releases/latest"
    
    import ssl
    import zipfile
    import io
    
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    req = urllib.request.Request(tag_url, headers={'User-Agent': 'poe-loot-filter-creator'})
    try:
        with urllib.request.urlopen(req, context=ctx) as response:
            data = json.loads(response.read().decode())
            zip_url = data.get('zipball_url')
            
            if zip_url:
                req2 = urllib.request.Request(zip_url, headers={'User-Agent': 'poe-loot-filter-creator'})
                with urllib.request.urlopen(req2, context=ctx) as resp2:
                    zip_data = resp2.read()
                    with zipfile.ZipFile(io.BytesIO(zip_data)) as z:
                        # Find the main 1-REGULAR.filter file inside the zip
                        target_file = None
                        for file_path in z.namelist():
                            # The main filter is in the root of the zip (excluding the top-level GitHub folder)
                            # e.g. NeverSinkDev-NeverSink-Filter-fe81f49/NeverSink's filter - 1-REGULAR.filter
                            if file_path.endswith("NeverSink's filter - 1-REGULAR.filter"):
                                target_file = file_path
                                break
                        
                        if target_file:
                            with z.open(target_file) as f:
                                content = f.read().decode('utf-8')
                                if content:
                                    # Save as backup
                                    save_filter_backup(content)
                                    return content
    except Exception as e:
        import traceback
        print(f"DEBUG: NeverSink Fetch Exception: {e}")
        print(traceback.format_exc())
        raise e
    
    return None

def save_filter_backup(content):
    """Saves the provided filter content to a backup file with a timestamp."""
    backup_dir = os.path.join(os.getcwd(), 'instance', 'backups')
    os.makedirs(backup_dir, exist_ok=True)
    
    # We keep two files: one for current content, one for metadata
    content_path = os.path.join(backup_dir, 'neversink_latest.filter')
    meta_path = os.path.join(backup_dir, 'neversink_meta.json')
    
    with open(content_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    with open(meta_path, 'w', encoding='utf-8') as f:
        json.dump({'timestamp': time.time()}, f)

def get_filter_backup():
    """Returns the content and timestamp of the latest backup filter."""
    backup_dir = os.path.join(os.getcwd(), 'instance', 'backups')
    content_path = os.path.join(backup_dir, 'neversink_latest.filter')
    meta_path = os.path.join(backup_dir, 'neversink_meta.json')
    
    if os.path.exists(content_path) and os.path.exists(meta_path):
        with open(content_path, 'r', encoding='utf-8') as f:
            content = f.read()
        with open(meta_path, 'r', encoding='utf-8') as f:
            meta = json.load(f)
        return content, meta.get('timestamp')
    
    return None, None

def assemble_filter(extracted_data, base_filter_text=None):
    """Combines custom blocks with the base filter."""
    custom_rules = generate_custom_blocks(extracted_data)
    if base_filter_text is None:
        base_filter_text = fetch_neversink_latest()
        
    return custom_rules + "\n" + base_filter_text
